version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/cloud_storage
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=art4000xxx
    volumes:
      - ./Uploads:/uploads
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=cloud_storage
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=art4000xxx
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: