server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/cloud_storage
    username: postgres
    password: art4000xxx
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

app:
  file-storage:
    path: /uploads
  jwt:
    secret: thisisaverylongsecretkeyforjwt1234567890
    expiration: 86400000